### PR TITLE
Fix --branch parameter

### PR DESCRIPTION
**Pull request by nathanchance**
Without this, trying to run `./build-llvm.py -b release/9.x` fails
when the last run was run with a default value for --branch.

### CODE REVIEW

**Comment by dileks** [comment]
I have not tested this and I like it.

**Comment by msfjarvis** [comment]
> I have not tested this and I like it.

Have you had a chance to test this yet? I'd really like to set some merges in motion to clear the review backlog.

**Comment by dileks** [comment]
Thanks for the friendly remainer.

Looks good to me.

Feel free to add my Tested-by.

```
[ log_tc-build.txt ]

Options:
projects: clang;lld
targets: X86
branch: release/9.x
stage1-opts: --build-stage1-only --install-stage1-only
misc-opts: --incremental
build-dir: /home/sdi/src/llvm-toolchain/build
install-dir: /home/sdi/src/llvm-toolchain/install

Already on 'release/9.x'
Your branch is behind 'origin/release/9.x' by 8 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
From git://github.com/llvm/llvm-project
 * branch                      release/9.x -> FETCH_HEAD
Updating 1e6b12dd3158..1634b4bc934d
Fast-forward
 .../clangd/GlobalCompilationDatabase.cpp           |   82 +-
 .../clangd/GlobalCompilationDatabase.h             |   16 +-
 clang-tools-extra/clangd/index/Serialization.cpp   |    4 +-
 clang-tools-extra/clangd/test/log.test             |    9 +
 clang-tools-extra/clangd/tool/ClangdMain.cpp       |  543 +-
 clang/docs/AttributeReference.rst                  | 5545 +++++++++++++++++++-
 clang/docs/ClangCommandLineReference.rst           |  355 +-
 clang/docs/DiagnosticsReference.rst                | 2596 ++++++---
 clang/docs/ReleaseNotes.rst                        |   33 +
 clang/include/clang/Basic/TargetInfo.h             |    8 +-
 clang/lib/AST/ASTContext.cpp                       |    2 +-
 clang/lib/AST/ItaniumCXXABI.cpp                    |    2 +-
 clang/lib/AST/MicrosoftCXXABI.cpp                  |    2 +-
 clang/lib/Basic/Targets/SPIR.h                     |    2 +-
 clang/lib/Basic/Targets/X86.h                      |    6 +-
 clang/lib/Sema/SemaDecl.cpp                        |    9 +-
 .../CodeGenOpenCLCXX/addrspace-derived-base.cl     |    4 +-
 clang/test/CodeGenOpenCLCXX/addrspace-of-this.cl   |   40 +-
 clang/test/CodeGenOpenCLCXX/addrspace-operators.cl |    8 +-
 .../test/CodeGenOpenCLCXX/addrspace-with-class.cl  |   30 +-
 .../method-overload-address-space.cl               |   14 +-
 .../CodeGenOpenCLCXX/template-address-spaces.cl    |    6 +-
 .../Sema/warn-uninitialized-statement-expression.c |   56 +
 .../test/functionalities/exec/TestExec.py          |    4 +-
 .../lldbsuite/test/functionalities/exec/main.cpp   |   82 +-
 .../Plugins/Process/Linux/NativeProcessLinux.cpp   |    9 +-
 llvm/test/Transforms/InstCombine/pow-exp.ll        |   18 +-
 llvm/test/Transforms/InstCombine/pow_fp_int.ll     |    6 +-
 28 files changed, 8274 insertions(+), 1217 deletions(-)
 create mode 100644 clang-tools-extra/clangd/test/log.test
 create mode 100644 clang/test/Sema/warn-uninitialized-statement-expression.c
Current branch release/9.x is up to date.
-- clang project is enabled
-- clang-tools-extra project is disabled
-- compiler-rt project is disabled
-- debuginfo-tests project is disabled
-- libclc project is disabled
-- libcxx project is disabled
-- libcxxabi project is disabled
-- libunwind project is disabled
-- lld project is enabled
-- lldb project is disabled
-- llgo project is disabled
-- openmp project is disabled
-- parallel-libs project is disabled
-- polly project is disabled
-- pstl project is disabled
-- Could NOT find Z3: Found unsuitable version "0.0.0", but required is at least "4.7.1" (found Z3_LIBRARIES-NOTFOUND)
-- Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR) 
-- Native target architecture is X86
-- Threads enabled.
-- Doxygen disabled.
-- Go bindings disabled.
-- Ninja version: 1.8.2
-- OCaml bindings disabled.
-- LLVM host triple: x86_64-unknown-linux-gnu
-- LLVM default target triple: x86_64-unknown-linux-gnu
-- Building with -fPIC
-- Constructing LLVMBuild project information
-- Linker detection: LLD
-- Targeting X86
-- Clang version: 9.0.0
-- LLD version: 9.0.0
-- Version: 0.0.0
-- Performing Test HAVE_THREAD_SAFETY_ATTRIBUTES -- failed to compile
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sdi/src/llvm-toolchain/build/stage1
[1/438] Generating VCSRevision.h
-- Found Git: /usr/bin/git (found version "2.20.1")
...<snip>
```

**Comment by msfjarvis** [comment]
Perfect, thanks Sedat. I'll merge this then.

**Pull request merged**
