### PR TITLE
build-llvm.py: LLVM's primary branch is now named "main"

### PR DESCRIPTION
**Pull request by nathanchance**
Link: https://foundation.llvm.org/docs/branch-rename/

### CODE REVIEW

**Review by msfjarvis — APPROVED** [review]
Do we need to be doing any migration on existing clones?

**Comment by nathanchance** [comment]
I am not sure it is worth building that into the script, we could just link to the foundation's page for people to do it manually.

**Comment by msfjarvis** [comment]
> I am not sure it is worth building that into the script, we could just link to the foundation's page for people to do it manually.

That works for me, wanna make the change?

**Comment by nathanchance** [comment]
Unfortunately, my time is rather limited right now. I could probably take a whack at it after the new year, unless you want to beat me to it :)

**Pull request merged**
