### PR TITLE
Add support for installing a single stage toolchain

### PR DESCRIPTION
**Pull request by nathanchance**
Some users do not want to be forced to do multi-stage builds and still
be able to install the compiled toolchain to a specific folder like the
multi-stage builds. This is added as an option as some users (like
myself) only use the stage 1 only flag as a tool for quicking testing
for build/runtimes issues during a bisect or checking to see if a patch
solves a problem (which was the original point of this flag).

As part of this shuffle, the installation print is moved into the
do_multistage_build function.

### CODE REVIEW

**Comment by dileks** [comment]
```
[ build_tc-build.sh ]
#!/bin/sh

export LANG=C
export LC_ALL=C

PROJECTS="clang;lld"
TARGETS="X86"

BRANCH="release/9.x"

WORKING_DIR=$(pwd)
BUILD_DIR="${WORKING_DIR}/build"
INSTALL_DIR="${WORKING_DIR}/install"

cd tc-build

./build-llvm.py -p "${PROJECTS}" -t "${TARGETS}" -b "${BRANCH}" -B "${BUILD_DIR}" -I "${INSTALL_DIR}" --build-stage1-only --install-stage1 --incremental --no-pull
```

Build-Log:
```
$ ./scripts/build_tc-build.sh 

========================
== Checking CC and LD ==
========================

CC: /usr/lib/llvm-9/bin/clang
CXX: /usr/lib/llvm-9/bin/clang++
LD: /usr/bin/ld.lld-9

===========================
== Checking dependencies ==
===========================

/usr/bin/cmake
/usr/bin/curl
/usr/bin/git
/usr/bin/ninja

==============================
== Configuring LLVM stage 1 ==
==============================

-- The C compiler identification is Clang 9.0.0
-- The CXX compiler identification is Clang 9.0.0
-- The ASM compiler identification is Clang
-- Found assembler: /usr/lib/llvm-9/bin/clang
-- Check for working C compiler: /usr/lib/llvm-9/bin/clang
-- Check for working C compiler: /usr/lib/llvm-9/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/llvm-9/bin/clang++
-- Check for working CXX compiler: /usr/lib/llvm-9/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- clang project is enabled
-- clang-tools-extra project is disabled
-- compiler-rt project is disabled
-- debuginfo-tests project is disabled
-- libclc project is disabled
-- libcxx project is disabled
-- libcxxabi project is disabled
-- libunwind project is disabled
-- lld project is enabled
-- lldb project is disabled
-- llgo project is disabled
-- openmp project is disabled
-- parallel-libs project is disabled
-- polly project is disabled
-- pstl project is disabled
-- Could NOT find Z3: Found unsuitable version "0.0.0", but required is at least "4.7.1" (found Z3_LIBRARIES-NOTFOUND)
-- Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR) 
-- Native target architecture is X86
-- Threads enabled.
-- Doxygen disabled.
-- Go bindings disabled.
-- Ninja version: 1.8.2
-- OCaml bindings disabled.
-- LLVM host triple: x86_64-unknown-linux-gnu
-- LLVM default target triple: x86_64-unknown-linux-gnu
-- Building with -fPIC
-- Constructing LLVMBuild project information
-- Linker detection: LLD
-- Targeting X86
-- Clang version: 9.0.0
-- LLD version: 9.0.0
-- Failed to find LLVM FileCheck
-- Version: 0.0.0
-- Performing Test HAVE_THREAD_SAFETY_ATTRIBUTES -- failed to compile
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sdi/src/llvm-toolchain/build/stage1

===========================
== Building LLVM stage 1 ==
===========================

[2/2] Linking CXX executable bin/llvm-config

LLVM build duration: 0:00:02

LLVM toolchain installed to: /home/sdi/src/llvm-toolchain/install

To use, either run:

    $ export PATH=/home/sdi/src/llvm-toolchain/install/bin:${PATH}

or add:

    PATH=/home/sdi/src/llvm-toolchain/install/bin:${PATH}

to the command you want to use this toolchain.
```

List install-dir:
```
$ LC_ALL=C ll install/
total 28
drwxr-xr-x  6 sdi sdi 4096 Jul 23 17:13 .
drwxr-xr-x 11 sdi sdi 4096 Jul 23 17:13 ..
-rw-r--r--  1 sdi sdi    1 Jul 23 17:13 .gitignore
drwxr-xr-x  2 sdi sdi 4096 Jul 23 17:13 bin
drwxr-xr-x  7 sdi sdi 4096 Jul 23 17:13 include
drwxr-xr-x  4 sdi sdi 4096 Jul 23 17:13 lib
drwxr-xr-x  4 sdi sdi 4096 Jul 23 17:13 share
```

**Comment by dileks** [comment]
For consistency reasons in naming I would rename the install option?
```
--build-stage1-only
--install-stage1-only
```

**Comment by nathanchance** [comment]
Sure, I can rename the option.

**Comment by dileks** [comment]
@nathanchance 
Thanks.

**Comment by MSF-Jarvis** [comment]
Any remaining blockers here?

**Comment by nathanchance** [comment]
Nope. Thanks for the review and testing all!

**Pull request merged**
