### PR TITLE
tc-build: Improvements around '--shallow-clone'

### PR DESCRIPTION
**Pull request by nathanchance**
Addresses #81 (cc @dileks) and some other things that I have thought of while investigating it.

I've written fairly detailed commit messages for each individual change. Some hammering on this would be appreciated as I think I have covered every corner case I can think of but I might have missed something.

@kdrag0n, please make sure this won't break your automated workflow.

### CODE REVIEW

**Comment by dileks** [comment]
What to do with "tc-build: Check ref exists before checking out when repo is shallow" patch?
Does apply on top of 4/4 patchset.

**Comment by dileks** [comment]
I tried (sorry partly German):
```
$ cd tc-build

$ ./build-llvm.py --branch release/10.x --shallow-clone

======================
== Downloading LLVM ==
======================

Klone nach '/home/dileks/src/llvm-toolchain/tc-build/llvm-project' ...
remote: Enumerating objects: 416201, done.
remote: Counting objects: 100% (416201/416201), done.
remote: Compressing objects: 100% (229094/229094), done.
remote: Total 416201 (delta 250839), reused 314868 (delta 179706), pack-reused 0
Empfange Objekte: 100% (416201/416201), 378.70 MiB | 2.48 MiB/s, Fertig.
Löse Unterschiede auf: 100% (250839/250839), Fertig.
Prüfe Konnektivität: 416201, Fertig.
Aktualisiere Dateien: 100% (91086/91086), Fertig.
Aktualisiere Dateien: 100% (28959/28959), Fertig.
Branch 'release/10.x' folgt nun Remote-Branch 'release/10.x' von 'origin'.
Zu neuem Branch 'release/10.x' gewechselt

$ cd llvm-project

$ git branch 
  master
* release/10.x

$ git branch -r
  origin/HEAD -> origin/master
  origin/master
  origin/release/1.0.x
  origin/release/1.1.x
  origin/release/1.2.x
  origin/release/1.3.x
  origin/release/1.4.x
  origin/release/1.5.x
  origin/release/1.6.x
  origin/release/1.7.x
  origin/release/1.8.x
  origin/release/1.9.x
  origin/release/10.x
  origin/release/2.0.x
  origin/release/2.1.x
  origin/release/2.2.x
  origin/release/2.3.x
  origin/release/2.4.x
  origin/release/2.5.x
  origin/release/2.6.x
  origin/release/2.7.x
  origin/release/2.8.x
  origin/release/2.9.x
  origin/release/3.0.x
  origin/release/3.1.x
  origin/release/3.2.x
  origin/release/3.3.x
  origin/release/3.4.x
  origin/release/3.5.x
  origin/release/3.6.x
  origin/release/3.7.x
  origin/release/3.8.x
  origin/release/3.9.x
  origin/release/4.x
  origin/release/5.x
  origin/release/6.x
  origin/release/7.x
  origin/release/8.x
  origin/release/9.x

$ git log --oneline -1
edbe962459da (grafted, HEAD -> release/10.x, origin/release/10.x) [COFF] Don't treat DWARF sections as GC roots

```

**Comment by dileks** [comment]
Just curious and bandwith limitation does not allow me to test...

What happens when a branch does not exist?
```
$ ./build-llvm.py --branch release/11.x --shallow-clone
```

Can I do a shallow-clone on `master` (default) and in a 2nd step for `release/10.x`?
```
$ ./build-llvm.py --shallow-clone
$ ./build-llvm.py --shallow-clone --branch release/10.x
```
...and get the same result like doing step #2 alone?

Is there an option for `clone-only` to shallow-clone without starting to build the toolchain?

**Comment by msfjarvis** [comment]
> Just curious and bandwith limitation does not allow me to test...
> 
> What happens when a branch does not exist?
> 
> ```
> $ ./build-llvm.py --branch release/11.x --shallow-clone
> ```

It fails after fetching master.

```
======================
== Downloading LLVM ==
======================

Cloning into '/mnt/mediahell/tc-build/llvm-project'...
remote: Enumerating objects: 416246, done.
remote: Counting objects: 100% (416246/416246), done.
remote: Compressing objects: 100% (229139/229139), done.
remote: Total 416246 (delta 250889), reused 314835 (delta 179704), pack-reused 0
Receiving objects: 100% (416246/416246), 378.67 MiB | 3.87 MiB/s, done.
Resolving deltas: 100% (250889/250889), done.
Updating files: 100% (91098/91098), done.
error: pathspec 'release/11.x' did not match any file(s) known to git
Traceback (most recent call last):
  File "./build-llvm.py", line 994, in <module>
    main()
  File "./build-llvm.py", line 987, in main
    ref)
  File "./build-llvm.py", line 519, in fetch_llvm_binutils
    subprocess.run(["git", "checkout", ref], check=True, cwd=cwd)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'checkout', 'release/11.x']' returned non-zero exit status 1.
```

> Can I do a shallow-clone on `master` (default) and in a 2nd step for `release/10.x`?

No. The script will tell you its impossible for it to do and that its time for manual intervention.

```
===================
== Updating LLVM ==
===================


Supplied ref (release/10.x) does not exist, cannot checkout.

To proceed, either:

	1. Manage the repo yourself and pass '--no-update' to the script.

	2. Run 'git -C /mnt/mediahell/tc-build/llvm-project fetch --unshallow origin' to get a complete repository.

	3. Delete '/mnt/mediahell/tc-build/llvm-project' and re-run the script with '-s' + '-b <ref>' to get a full set of refs.

```

> Is there an option for `clone-only` to shallow-clone without starting to build the toolchain?

No, that makes little sense in what is supposed to be a build script.

**Comment by dileks** [comment]
Thanks you @msfjarvis and @nathanchance for making this happen!

We are very close to get a Green-IT award.

**Pull request merged**
