### PR TITLE
build-llvm.py: Avoid LLVMgold unless using ld.gold and lto

### PR DESCRIPTION
**Pull request by kees**
Don't build LLVMgold if we don't absolutely have to.

Signed-off-by: Kees Cook <keescook@chromium.org>

### CODE REVIEW

**Comment by nathanchance** [comment]
I like it but I think we can go a step further and just get rid of these binutils defines altogether. The only reason we built the gold plugin in the first place was for supporting LTO on the Pixel 3, which used `ld.gold` instead of `ld.lld` like Android 4.14+ and mainline; now that the Pixel 3 is EOL, it seems reasonable to remove this. If people need it, they can bring it back via `--defines`.

With that, we can actually rip out much of `utils.py` and stick it in `build-binutils.py`, as `build-llvm.py` will no longer need to know about binutils at all. If you feel like tackling that, be my guest, otherwise I can do it soon.

**Comment by kees** [comment]
Hm, I'm not sure I know all the dependencies (or at least history) of how tc-build gets used, so I suspect it would take a while for me to do what you're suggesting. Without this minimal proposed change, though, I can't build (since I don't have gold installed and don't want it installed).

**Comment by nathanchance** [comment]
Oh, can I see the error that you get? I did not realize that building the gold plugin required `ld.gold` to already be installed...

**Comment by kees** [comment]
> Oh, can I see the error that you get? I did not realize that building the gold plugin required `ld.gold` to already be installed...

Running:
```
~/src/tc-build/build-llvm.py \
        -i \
        -l "$PROJECT" \
        --lto thin \
        -B "$STAGE3" \
        -I "$INSTALL" \
        --build-stage1-only --install-stage1-only
```

I get:

```
...
===========================                                                                                                            
== Building LLVM stage 1 ==                                                                                                            
===========================                                                                                                            
                                                                                                                                       
[4277/5686] Building CXX object tools/gold/CMakeFiles/LLVMgold.dir/gold-plugin.cpp.o                FAILED: tools/gold/CMakeFiles/LLVMgold.dir/gold-plugin.cpp.o                                                                                                              
CCACHE_CPP2=yes CCACHE_HASHDIR=yes /usr/bin/ccache /home/kees/src/built-compilers/llvm/stage3-3291eac12340f465084f347720d99352241f621c-tc/install/bin/clang++ -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/kees/src/built-compilers/llvm/stage3-88db516af69619d4326edea37e52fc7321c33bb5/stage1/tools/gold -I/home/kees/src/llvm-project/llvm/tools/gold -I/home/kees/src/built-compilers/llvm/stage3-88db516af69619d4326edea37e52fc7321c33bb5/stage1/include -I/home/kees/src/llvm-project/llvm/include -I/home/kees/src/tc-build/binutils-2.39/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -w -fdiagnostics-color -ffunction-sections -fdata-sections -flto=thin -O3 -DNDEBUG -fPIC  -fno-exceptions -fno-rtti -std=c++17 -MD -MT tools/gold/CMakeFiles/LLVMgold.dir/gold-plugin.cpp.o -MF tools/gold/CMakeFiles/LLVMgold.dir/gold-plugin.cpp.o.d -o tools/gold/CMakeFiles/LLVMgold.dir/gold-plugin.cpp.o -c /home/kees/src/llvm-project/llvm/tools/gold/gold-plugin.cpp
/home/kees/src/llvm-project/llvm/tools/gold/gold-plugin.cpp:38:10: fatal error: 'plugin-api.h' file not found                          
#include <plugin-api.h>                                                                                                                
         ^~~~~~~~~~~~~~                                                                                                                
1 error generated.                                                                                                                     
```

**Comment by nathanchance** [comment]
Ah, it seems like you might just be missing the `binutils-dev` package? Regardless, this should all go. Let me draft up a pull request real quick for you to test.

**Comment by kees** [comment]
Redundant to just entirely removing gold. :)

**Pull request closed without merging**
