### PR TITLE
build-llvm.py: Look for clang-11 when building stage 1

### PR DESCRIPTION
**Pull request by nathanchance**
Also, add a variable so this becomes easier to bump. Eventually, I would like to do this similar to `driver.sh` in the CI repo where we just grab the latest version from the LLVM repo but that becomes hard in Python...

### CODE REVIEW

**Comment by msfjarvis** [comment]
> Also, add a variable so this becomes easier to bump. Eventually, I would like to do this similar to `driver.sh` in the CI repo where we just grab the latest version from the LLVM repo but that becomes hard in Python...

[Holy mother of Bash hacks](https://github.com/ClangBuiltLinux/continuous-integration/blob/999014f5d3a48231833a2aa22c79ca2711472d9c/driver.sh#L183)... I'll see if I can port this somehow.

**Comment by nathanchance** [comment]
> [Holy mother of Bash hacks](https://github.com/ClangBuiltLinux/continuous-integration/blob/999014f5d3a48231833a2aa22c79ca2711472d9c/driver.sh#L183)...

Don’t hate on my bash :(

> I'll see if I can port this somehow.

But thank you, a good Python solution would be great so we can avoid manually bumping :)

**Comment by msfjarvis** [comment]
Maybe we should just use the local copy of the file?

**Comment by nathanchance** [comment]
No, if the script is being run for the first time, we won’t have the repo.

The main issue I foresee with this is the script won’t work without internet now. Before this, if `--no-update` were passed, there would be no need for internet but now this requires it. Not sure how much that actually matters and in reality, we could just have the fallback if we can’t reach the URL.

**Comment by msfjarvis** [comment]
Yeah that's what I thought. I'll add a fallback to clang 11.

**Comment by nathanchance** [comment]
Thanks :)

**Comment by msfjarvis** [comment]
Well that took a while. Confirmed the test cases that came to mind

- [x] Internet connected, LLVM 11 snapshot installed, tc-build uses {clang,lld}-11
- [x] Internet disconnected, LLVM 11 snapshot installed, tc-build uses {clang,lld}-11
- [x] Internet disconnected, LLVM 11 snapshot installed, tc-build master uses {clang,lld}-10
- [x] Internet connected, LLVM 11 snapshot installed, tc-build master uses {clang,lld}-10

**Comment by msfjarvis** [comment]
image

**Pull request merged**
