### PR TITLE
tc-build: Add initial scripts and update README

### PR DESCRIPTION
**Pull request by nathanchance**
Review away (and add reviewers as necessary)

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
probably won't be able to provide a quick review (this week or next), hopefully we can wait for that.

**Comment by nathanchance** [comment]
That's fine, that will also give time for others to test and review.

**Comment by ojeda** [comment]
A few quick comments:

  * Since we are downloading files here, we should verify them for the user too. Since we download only particular ones, I suggest to keep the SHA-256 hash in the repo and verify it before the `curl`. This avoids depending on `gpg` and playing with keyrings.

  * Commenting why each `CMAKE_DEFINES` option was added would be nice, even if it is a one-liner. I know details can be found in the various LLVM's `CMakeLists.txt`s etc., but it takes time to re-discover the reasoning behind each (and why we added it in these scripts in particular) if you are not working all day within LLVM.

  * (Don't hate me with this one :) In cases like this, I always suggest to use a proper language for this stuff (e.g. Python), even if it introduces a dependency. These `sh` scripts seem already complex enough to warrant it, but I know it is a pain to rewrite now that you are done. Python's `argparse` in particular is very nice for this, and also avoids `-usage.txt` files etc.

**Comment by nathanchance** [comment]
> Since we are downloading files here, we should verify them for the user too.

Great idea, done: https://github.com/nathanchance/tc-build/commit/29eeff97176aeab32e3bb01537d16b763c6a4323

> Commenting why each `CMAKE_DEFINES` option was added would be nice, even if it is a one-liner.

I agree: https://github.com/ClangBuiltLinux/tc-build/commit/2065cac9fc9a9b8c2f35b8b4276a5f241dfec4ae

> I know it is a pain to rewrite now that you are done

Also not to mention that I don't know Python :) but yes, I suppose I should probably learn it so that stuff like this can be more readable to others.

**Comment by nishanthkarthik** [comment]
@nathanchance I have some experience with python. If we list the project roadmap, I can contribute too!

**Comment by MSF-Jarvis** [comment]
> @nathanchance I have some experience with python. If we list the project roadmap, I can contribute too!

I can help with that :+1:

**Comment by ojeda** [comment]
@nathanchance That was quick! :)

Thanks a lot!

> Great idea, done: [nathanchance@29eeff9](https://github.com/nathanchance/tc-build/commit/29eeff97176aeab32e3bb01537d16b763c6a4323)

I am not sure what you mean by:

    This avoids gpg shenanigans even though it'd be more secure.

Checking signatures is useful because it is a way to verify any possible future new files (or hashes) signed by the same people. However, in this case we have a known file (which you verified its authenticity using the signature before computing the hash), so unless SHA-256's second preimage resistance is broken, I don't see how signatures add anything here.

> I agree: [nathanchance@2065cac](https://github.com/nathanchance/tc-build/commit/2065cac9fc9a9b8c2f35b8b4276a5f241dfec4ae)

Great! Some are obvious, of course, but the ones that aren't are very useful. Quick note on `LLVM_ENABLE_BINDINGS`: there are more than OCaml bindings, no? (Python and Go AFAICS in `llvm/bindings`). Maybe copy-paste error?

> Also not to mention that I don't know Python :) but yes, I suppose I should probably learn it so that stuff like this can be more readable to others.

I didn't mean shell scripts are unreadable [*], but that as soon as shell scripts get complex enough (loops, testing, handling lists, etc.), it is usually nicer to do this stuff in Python (or the like) instead, in my opinion. I had to maintain both shell scripts and Python scripts for similar stuff in the past and nowadays I basically never write any shell scripts anymore unless they are shorter than 10 lines!

Python 100% recommended if you have the time to take a look at it. But don't worry about rewriting this, of course, unless somebody feels up for it.

[*] They are, though ;D

**Comment by nathanchance** [comment]
> @nathanchance That was quick! :)
> 
> > Great idea, done: [nathanchance@29eeff9](https://github.com/nathanchance/tc-build/commit/29eeff97176aeab32e3bb01537d16b763c6a4323)
> 
> Thanks a lot! I am not sure what you mean by:
> 
> ```
> This avoids gpg shenanigans even though it'd be more secure.
> ```
> Checking signatures is useful because it is a way to verify any possible future new files (or hashes) signed by the same people. However, in this case we have a known file (which you verified its authenticity using the signature before computing the hash), so unless SHA-256's second preimage resistance is broken, I don't see how signatures add anything here.

Yes, you're right, I'll remove that line.

> > I agree: [nathanchance@2065cac](https://github.com/nathanchance/tc-build/commit/2065cac9fc9a9b8c2f35b8b4276a5f241dfec4ae)
> 
> Great! Some are obvious, of course, but the ones that aren't are very useful. Quick note on `LLVM_ENABLE_BINDINGS`: there are more than OCaml bindings, no? (Python and Go AFAICS in `llvm/bindings`). Maybe copy-paste error?

Yes (although I never actually looked into the bindings folder).

> > Also not to mention that I don't know Python :) but yes, I suppose I should probably learn it so that stuff like this can be more readable to others.
> 
> I didn't mean shell scripts are unreadable [*], but that as soon as shell scripts get complex enough (loops, testing, handling lists, etc.), it is usually nicer to do this stuff in Python (or the like) instead, in my opinion. I had to maintain both shell scripts and Python scripts for similar stuff in the past and nowadays I basically never write any shell scripts anymore unless they are shorter than 10 lines!
> 
> Python 100% recommended if you have the time to take a look at it. But don't worry about rewriting this, of course, unless somebody feels up for it.
> 
> [*] They are, though ;D

I won't necessarily mind if someone rewrites this but at the same time, I won't feel comfortable maintaining it.

**Comment by E5ten** [comment]
I'd say that even if someone who knew python was willing to rewrite it, in my opinion shell scripts are significantly better for this, they get the job done without adding a dependency, and the build they're automating would be done using commands in a shell if not automated, so it's much easier to understand when the automation is done in a shell script instead of python.

**Comment by ojeda** [comment]
> and the build they're automating would be done using commands in a shell if not automated, so it's much easier to understand when the automation is done in a shell script instead of python.

That holds true if your shell script consisted only of a series of commands to be executed sequentially, the same way you did in the shell manually. But as soon as your shell script starts making decisions, takes parameters/flags, you document those parameters, etc. then you are not doing what you did in the terminal. Instead, it begins to look like an actual program, and for writing actual programs, there are better choices out there.

**Comment by nickdesaulniers** [comment]
> Also not to mention that I don't know Python :) but yes, I suppose I should probably learn it

Having a smallish project that you're interested in is always a great opportunity to learn a new language.

**Comment by nathanchance** [comment]
> Having a smallish project that you're interested in is always a great opportunity to learn a new language.

Fair point, I'll see if I can find some time soon to read up about it and see how complicated it would be to rewrite these.

**Comment by ojeda** [comment]
If you need any help, don't be shy to contact! If you end doing it, don't get overwhelmed by Python's huge standard library. To do this kind of stuff, the most important ones you will want to use are:

  * [`subprocess`](https://docs.python.org/3/library/subprocess.html) for calling processes (and handling their return codes, output, piping, etc. etc.).
  * [`argparse`](https://docs.python.org/3/library/argparse.html) for building a full CLI, including sub-commands a la Git.
  * [`pathlib`](https://docs.python.org/3/library/pathlib.html) for handling paths properly.
  * [`shutil`](https://docs.python.org/3/library/shutil.html) for the usual filesystem operations.
  * [`logging`](https://docs.python.org/3/library/logging.html) is very useful even on its basic form to avoid doing raw prints and to aid on debugging.

There are other related modules, but those tend to be either lower-level or older equivalents (typically with less features or more awkward to use). As a general guideline, try to avoid the `os` module in particular if you can do it with one of the others, as well as the `getopt` one.

**Comment by nathanchance** [comment]
I am currently rewriting this in Python, progress can be tracked here: https://github.com/ClangBuiltLinux/tc-build/commits/msf/python-bringup

Please feel free to review as I go if you see something that can be improved. I hope to have a v2 pull request by tonight but we'll see how testing goes :)

Closing this now.

**Comment by nickdesaulniers** [comment]
Looks great so far!  @gwelymernans wrote a python linter; if you really want the hardcore "google3 python readability" review, maybe he can spare some cycles for it?  (surviving "google3 c++ readability" made me a much much much better C++ programmer).

**Comment by nickdesaulniers** [comment]
The README could be flushed out.  It should address questions like:
1. what is this repo?
2. why does it exist?
3. how do I run it?

Needs a LICENSE file.

**Comment by nathanchance** [comment]
> @gwelymernans wrote a python linter; if you really want the hardcore "google3 python readability" review, maybe he can spare some cycles for it?

Please, I was planning on linting it once I was done writing it.

> The README could be flushed out. Needs a LICENSE file.

Copy. Those two will come from this pull and I'll tidy them up.

**Comment by gwelymernans** [comment]
The reformatter is at https://github.com/google/yapf :-)

**Pull request closed without merging**
