### PR TITLE
utils.py: Update to binutils 2.40

### PR DESCRIPTION
**Pull request by najahiiii**
Signed-off-by: Ahmad Thoriq Najahi <najahi@zephyrus.id>

### CODE REVIEW

**Review by nathanchance — APPROVED** [review]
Thanks for the patch!

**Review by nathanchance — CHANGES_REQUESTED** [review]
Actually, it looks like `yapf` is not happy with the URL change. Please run it locally or manually apply the diff that CI suggests.

**Comment by najahiiii** [comment]
Updated

**Comment by nathanchance** [comment]
Let's use an f-string for this to satisfy both `flake8` and `yapf` (hopefully...):

```
f"https://sourceware.org/pub/binutils/releases/{binutils_tarball.name}"
```

**Comment by najahiiii** [comment]
Updated, passed both pylint check locally.

**Review by nathanchance — APPROVED** [review]

**Pull request merged**
