### PR TITLE
build-llvm.py: Some improvements around '--build-stage1-only' and optimization options

### PR DESCRIPTION
**Pull request by nathanchance**
The commit messages should be self explanatory.

### CODE REVIEW

**Review by msfjarvis — APPROVED** [review]

**Comment by dileks** [comment]
The new text is an improvment to the right direction.

Reviewed-by: /me

**Comment by nathanchance** [comment]
I will try to further flush out the implications of PGO and LTO in a few hours. Please do not merge until I do that.

**Comment by nathanchance** [comment]
I will not be able to test the `--linux-src` option until later but let me know if everything else looks good to you @dileks

**Comment by nathanchance** [comment]
Alright, some re-review would be appreciated, I think this should address all of @dileks 's concerns :)

**Comment by dileks** [comment]
Looks good to me - will try.

Is there an easy way to get the patches from your remote Git?

**Comment by nathanchance** [comment]
```
git pull https://github.com/nathanchance/tc-build pgo-lto-stage1
```

in an existing tc-build tree will probably be easiest!

**Comment by dileks** [comment]
Thanks.

I was looking into...

[1] https://github.com/nathanchance/tc-build/branches

**Review by msfjarvis — APPROVED** [review]

**Comment by dileks** [comment]
The `-L LINUX_FOLDER, --linux-folder LINUX_FOLDER` option worked as expected means `my local Linux Git` was used for `PGO profiling` and there was no need to download a Linux-kernel release tarball.

Please, see my updates in #109.

This is a nice improvement.
Thanks @nathanchance

**Comment by nathanchance** [comment]
Thanks @dileks

**Pull request merged**
