### PR TITLE
Make script more friendly to being used system-wide/LLVM development and add more kernel PGO options

### PR DESCRIPTION
**Pull request by nathanchance**
I tried to keep all of the commits self explanatory, yell at me if something needs to be expanded upon or done differently :)

cc @kees because I saw you doing PGO based on allmodconfig.

### CODE REVIEW

**Review by msfjarvis — APPROVED** [review]
Commits all look good, I haven't had a chance to test all the new configurations personally but I assume you have.

**Comment by nathanchance** [comment]
I ended up uncovering an issue with the last patch; I am testing the fix then I will force push and merge. Thanks for the review!

**Review by kees — APPROVED** [review]
Looks good! I swear to switch my local builds to tc-build soon! :)

**Comment by dileks** [comment]
Personally, I do not like mega series of patches with touching different areas in one pull-request.
But hey linux-stable has sometime 200+/300+/400+ patches from one kernel-patchlevel-version to the next :-)

For example the kernel-version bump or mips/malta_defconfig could be separate patches.

I like some ideas in the PGO part and am very interested in seeing what allmodconfig=yes on x86-64 gives for a benefit.
Note: Check a normal defconfig of x86-64 and arm64 :-)...
( This is here build-times of 00:45 vs. 02:30 [hh:mm] when using both arch-targets. )

Just as a wish:
How about an option to pass a custom kernel-config (with)in the PGO optimization stage.

Thanks for the patch-series.

**Comment by dileks** [comment]
My `build-llvm.py` line looks like this:
```sh
python3 ./build-llvm.py --no-update --build-type Release -p clang;lld -t X86;BPF --clang-vendor dileks -B /home/dileks/src/llvm-toolchain/build -I /opt/llvm-toolchain --check-targets clang lld --build-stage1-only --install-stage1-only -D LLVM_PARALLEL_LINK_JOBS=1 --show-build-commands
```

`build-llvm.py` says:
```sh
    parser.add_argument("--show-build-commands",
                        help=textwrap.dedent("""\
                        By default, the script only shows the output of the comands it is running. When this option
                        is enabled, the invocations of cmake, ninja, and kernel/build.sh will be shown to help with
                        reproducing issues outside of the script.

                        """),
                        action="store_true")
```

My build-log looks as usual - for example I do not see any `ninja` invocations.

Just curious if this is different for a `stage1-only` build.

( I can attach my build-log when the build has finished. )

**Comment by dileks** [comment]
OK, I see what is meant with `cmake` and `ninja` invocations:
```
========================
== Checking CC and LD ==
========================

CC: /usr/lib/llvm-12/bin/clang
CXX: /usr/bin/clang++-12
LD: /usr/bin/ld.lld-12

===========================
== Checking dependencies ==
===========================

/usr/bin/cmake
/usr/bin/curl
/usr/bin/git
/usr/bin/ninja

==============================
== Configuring LLVM stage 1 ==
==============================

$ cmake -G Ninja -Wno-dev -DCLANG_ENABLE_ARCMT=OFF -DCLANG_ENABLE_STATIC_ANALYZER=OFF -DCLANG_PLUGIN_SUPPORT=OFF -DLLVM_ENABLE_BINDINGS=OFF -DLLVM_ENABLE_OCAMLDOC=OFF -DLLVM_EXTERNAL_CLANG_TOOLS_EXTRA_SOURCE_DIR= -DLLVM_INCLUDE_DOCS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DCMAKE_AR=/usr/lib/llvm-12/bin/llvm-ar -DCMAKE_C_COMPILER=/usr/lib/llvm-12/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++-12 -DLLVM_USE_LINKER=/usr/bin/ld.lld-12 -DCMAKE_RANLIB=/usr/lib/llvm-12/bin/llvm-ranlib -DLLVM_ENABLE_PROJECTS=clang;compiler-rt;lld;polly -DCOMPILER_RT_BUILD_LIBFUZZER=OFF -DCOMPILER_RT_BUILD_BUILTINS=OFF -DCOMPILER_RT_BUILD_CRT=OFF -DCOMPILER_RT_BUILD_XRAY=OFF -DLLVM_TARGETS_TO_BUILD=X86;BPF -DLLVM_CCACHE_BUILD=ON -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_WARNINGS=OFF -DCMAKE_INSTALL_PREFIX=/opt/llvm-toolchain -DCMAKE_C_FLAGS= -DCMAKE_CXX_FLAGS= -DLLVM_BINUTILS_INCDIR=/home/dileks/src/llvm-toolchain/git/binutils-2.36.1/include -DLLVM_ENABLE_PLUGINS=ON -DCLANG_VENDOR=dileks -DLLVM_ENABLE_TERMINFO=OFF -DLLVM_PARALLEL_LINK_JOBS=1 /home/dileks/src/llvm-toolchain/git/llvm-project/llvm

===========================
== Building LLVM stage 1 ==
===========================

$ ninja
$ ninja check-clang check-lld

LLVM build duration: 4:09:42

LLVM toolchain installed to: /opt/llvm-toolchain

To use, either run:

    $ export PATH=/opt/llvm-toolchain/bin:${PATH}

or add:

    PATH=/opt/llvm-toolchain/bin:${PATH}

to the command you want to use this toolchain.

Version information:

```

**Pull request merged**
